### ISSUE TITLE
Error opening `GeoIP2-City-Test.mmdb` with maxmind.open

### ISSUE THREAD

**Issue by evvvvr** [maxmind/MaxMind-DB#99]
Hello,

This:
```typescript
await maxmind.open<CityResponse>('./test-data/GeoIP2-City-Test.mmdb');
```

ends-up in:
```
Error: Unknown type 17 at offset 1                                    
        at Decoder.decodeByType (node_modules/mmdb-lib/src/decoder.ts:131:11)
        at Decoder.decode (node_modules/mmdb-lib/src/decoder.ts:78:17)
        at Object.<anonymous>.exports.parseMetadata (node_modules/mmdb-lib/src/metadata.ts:28:28)
        at Reader.load (node_modules/mmdb-lib/
src/index.ts:25:21)
        at new Reader (node_modules/mmdb-lib/src/index.ts:20:10)
        at Object.open (node_modules/maxmind/s
rc/index.ts:36:18)
```
```
"maxmind@npm:^4.3.2":
  version: 4.3.2
  resolution: "maxmind@npm:4.3.2"
  dependencies:
    mmdb-lib: 1.3.0
```
